### PR TITLE
Upgrade lib

### PR DESCRIPTION
**Pull request by HoaiDang-work**
I forked your sample project and modified it to upgrade to latest libs and add some more examples.

### CODE REVIEW

**Comment by pjfanning** [comment]
Thanks - looks good

**Comment by pjfanning** [comment]
Apologies - I reverted this (but kept it in a new branch called 'rework').

I hadn't noticed this before I merged:
```
  "com.github.swagger-akka-http" %% "swagger-akka-http" % "2.4.2",
  "io.swagger" % "swagger-jaxrs" % "1.5.18"
```

This basically loads the old style swagger (swagger-jaxrs 1.5.18) and the new style swagger. I don't think the 2 should be mixed.

**Comment by pjfanning** [comment]
I made a few small changes to your code (https://github.com/pjfanning/swagger-akka-http-sample-java/tree/rework).

There are still a few uses of `io.swagger.annotations` annotations -- can this be changed to swagger.v3 annotations?

**Comment by HoaiDang-work** [comment]
Thanks!

**Comment by pjfanning** [comment]
I've remerged this to master branch now after making changes to remove the old swagger dependencies.

**Pull request merged**
